apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: oai-mep-registry
  name: oai-mep-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: oai-mep-registry
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/oai-mep: "true"
        io.kompose.service: oai-mep-registry
    spec:
      containers:
        - env:
            - name: BACKEND
              value: oai-mep-gateway-service:8001 #oai-mep-gateway-service:8001
            - name: CONFIG_FILE
              value: /usr/local/etc/configuration.yaml
            - name: DATABASE_HOST
              value: mongodb
            - name: DATABASE_PASSWORD
              value: linux
            - name: DATABASE_PORT
              value: "27017"
            - name: DATABASE_USER
              value: admin
            - name: FQDN
              value: oai-mep-gateway-service #oai-mep-gateway-service
            - name: HOST
              value: oai-mep-registry #0.0.0.0 #172.29.248.6
            - name: LOG_LEVEL
              value: info
            - name: MOUNT_CONFIG
              value: "no"
            - name: PORT
              value: "80"
            - name: RESET_DATABASE
              value: "yes"
          image: localhost:32000/oai-mep:latest #oaisoftwarealliance/oai-mep:latest
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
                - /bin/sh -c "pgrep oai_mep"
            failureThreshold: 5
            periodSeconds: 5
            timeoutSeconds: 5
          name: oai-mep-registry
          ports:
            - containerPort: 80
              hostPort: 48154
              protocol: TCP
      hostname: oai-mep-registry #oai-mep-registry.org
      restartPolicy: Always
