apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: mongodb
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/oai-mep: "true"
        io.kompose.service: mongodb
    spec:
      containers:
        - args:
            - mongod
          env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: linux
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
          image: mongo:latest
          livenessProbe:
            exec:
              command:
                - /bin/sh -c "pgrep mongod"
            failureThreshold: 5
            periodSeconds: 5
            timeoutSeconds: 5
          name: oai-registry-db
          ports:
            - containerPort: 27017
              hostPort: 27017
              protocol: TCP
      restartPolicy: Always
