apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-test-app
spec:
  selector:
    matchLabels:
      app: flask-test-app
  template:
    metadata:
      labels:
        app: flask-test-app
    spec:
      containers:
        - name: flask-test-app
          image: localhost:32000/flask-app:debug
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 10"]
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: config-volume
              mountPath: /app/configuration.yaml
              subPath: configuration.yaml
            - name: descriptor-volume
              mountPath: /app/hello-world-descriptor.yaml
              subPath: hello-world-descriptor.yaml
      volumes:
        - name: config-volume
          configMap:
            name: configuration-file
        - name: descriptor-volume
          configMap:
            name: descriptor-file
      terminationGracePeriodSeconds: 30
