apiVersion: batch/v1
kind: Job
metadata:
  name: kong-migration-job
spec:
  template:
    spec:
      containers:
      - name: kong-migration-container
        image: kong:3.0-alpine
        command: ["kong", "migrations", "bootstrap"]
        env:
        - name: KONG_PG_HOST
          value: oai-mep-gateway-db
        - name: KONG_PG_PASSWORD
          value: kong
      restartPolicy: Never

